AWSTemplateFormatVersion: 2010-09-09
Description: |
  This template launches an EC2 with a security group that enables SSH connection.
  
Resources:
  MyEc2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-02e136e904f3da870
      InstanceType: t2.micro
      KeyName: firstkey # please use your own key
      SecurityGroups:
        - FirstSecurityGroup
      Tags:
        - Key: Name
          Value: charlie-cf-stack-ec2
        - Key: Department
          Value: HR


